### ISSUE TITLE
Automate Docker Hub publishing from GitHub Actions

### ISSUE THREAD

**Issue by erseco** [giocomai/omeka-s-docker#13]
Currently, the GitHub Actions workflow builds and pushes Docker images to GHCR (`ghcr.io`). However, it would be beneficial to **also push images to Docker Hub** automatically when new versions are tagged or branches are pushed.

This would make it easier for users who rely on Docker Hub to get the latest updates without having to build the image themselves.

### 🛠 Required changes

1. **Update `docker/login-action` to also log in to Docker Hub:**

Add another login step **before** the `docker/build-push-action` steps:

```yaml
- name: Log in to Docker Hub
  uses: docker/login-action@v3
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}
```

2. **Update the list of images in `docker/metadata-action`:**

```yaml
with:
  images: |
    ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    docker.io/${{ secrets.DOCKERHUB_USERNAME }}/omeka-s-docker
```

This will allow publishing to a user-specific Docker Hub repository and work seamlessly with forks, as long as the secrets are defined.

3. **Update `tags` in both `build-and-push` blocks to include Docker Hub:**

```yaml
tags: |
  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  docker.io/${{ secrets.DOCKERHUB_USERNAME }}/omeka-s-docker:${{ steps.tag.outputs.tag }}
  docker.io/${{ secrets.DOCKERHUB_USERNAME }}/omeka-s-docker:latest
```

(Apply this in both the tag and branch push blocks.)

### 🔐 Required secrets in GitHub repo or fork settings

* `DOCKERHUB_USERNAME`: your Docker Hub username
* `DOCKERHUB_TOKEN`: a [Docker Hub access token](https://docs.docker.com/security/for-developers/access-tokens/), recommended over using a password

---

Let me know if you'd like a PR with the proposed changes.
